$template = Get-Content -Raw "dest_template.html"

$pages = @(
    @{
        FILE = "singapore.html"
        TITLE = "Singapore"
        HERO_IMG = "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=1600"
        HERO_TITLE = "Experience Singapore"
        HERO_SUBTEXT = "A mesmerizing blend of nature and futuristic marvels."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1565967511849-76a60a516170?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Singapore"
        WHY_VISIT_PARA = "Immerse yourself in a garden city where the future is intertwined with tradition. Experience immaculate parks, ultra-modern architecture, and a cultural melting pot that tantalizes all senses. It is a stunning display of luxury and efficiency."
        BULLET_1 = "Supertrees and cloud forests"
        BULLET_2 = "World-class Changi Airport attractions"
        BULLET_3 = "Michelin-starred street food"
        BULLET_4 = "Luxury hotels with infinity pools"
        BULLET_5 = "Clean, green, and wonderfully organized"
        EXP_TITLE = "Modern Marvels"
        EXP_1_IMG = "https://images.unsplash.com/photo-1542617639-652a922ff1e1?q=80&w=600"
        EXP_1_TITLE = "Gardens by the Bay"
        EXP_1_PARA = "Stroll beneath towering supertrees and step inside giant glass biomes brimming with exotic plants."
        EXP_2_IMG = "https://images.unsplash.com/photo-1620023605809-5a9e3cc2edcc?q=80&w=600"
        EXP_2_TITLE = "Marina Bay Luxury"
        EXP_2_PARA = "Stay at iconic infinity pools hanging gracefully above the magnificent skyline."
        EXP_3_IMG = "https://images.unsplash.com/photo-1570773663046-5ef10dfd04ed?q=80&w=600"
        EXP_3_TITLE = "Cultural Enclaves"
        EXP_3_PARA = "Wander through Chinatown and Little India, experiencing the roots of Singapore."
        STORY_TITLE = "A City in a Garden"
        STORY_PARA = "From sunrise walks along the Marina to dramatic light shows fading into the night, Singapore is pure magic."
        GAL_1 = "https://images.unsplash.com/photo-1505315570081-37d363b9ef7a?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1534947990520-25e98f01b1de?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1620023605809-5a9e3cc2edcc?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1513635269975-59693e0cd8ce?q=80&w=800"
    }
    @{
        FILE = "europe.html"
        TITLE = "Europe"
        HERO_IMG = "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?q=80&w=1600"
        HERO_TITLE = "Experience Europe"
        HERO_SUBTEXT = "A timeless journey through art, culture, and majestic landscapes."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1522814890693-010e9fcb9be2?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Europe"
        WHY_VISIT_PARA = "Step into a living museum where ancient castles overlook breathtaking coastlines and romantic cityscapes. Europe offers a tapestry of cultures, world-renowned gastronomy, and history told through cobblestone streets. It is an exploration of the highest order, where every country gifts a new luxury to uncover."
        BULLET_1 = "Iconic landmarks like the Eiffel Tower and Colosseum"
        BULLET_2 = "Exclusive wine tastings in the Mediterranean"
        BULLET_3 = "Serene gondola rides and pristine alpine resorts"
        BULLET_4 = "Centuries of stunning Renaissance art and architecture"
        BULLET_5 = "Seamless luxury train journeys across borders"
        EXP_TITLE = "Timeless Elegance"
        EXP_1_IMG = "https://images.unsplash.com/photo-1502602898657-3e907fa8ba0b?q=80&w=600"
        EXP_1_TITLE = "Historic Architecture"
        EXP_1_PARA = "Wander beneath Gothic arches and Renaissance domes that have stood the test of time."
        EXP_2_IMG = "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=600"
        EXP_2_TITLE = "Culinary Journeys"
        EXP_2_PARA = "Indulge in authentic Italian pasta, French cheeses, and fine regional wines."
        EXP_3_IMG = "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?q=80&w=600"
        EXP_3_TITLE = "Scenic Alps"
        EXP_3_PARA = "Breathe in the crisp mountain air of majestic snow-capped peaks and sapphire lakes."
        STORY_TITLE = "A Renaissance Dream"
        STORY_PARA = "Whether savoring a croissant by the Seine or cruising the Amalfi Coast, Europe makes every passing second feel like a cinematic masterpiece."
        GAL_1 = "https://images.unsplash.com/photo-1473625247510-8b1b5188f615?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1515586835226-9a008b87ec2d?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1520106212299-d99c443e4568?q=80&w=800"
    }
    @{
        FILE = "uk.html"
        TITLE = "United Kingdom"
        HERO_IMG = "https://images.unsplash.com/photo-1513635269975-59693e0cd8ce?q=80&w=1600"
        HERO_TITLE = "Experience the UK"
        HERO_SUBTEXT = "Discover royal heritage and breathtaking countryside."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1505322022379-7c3353ee6291?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit the UK"
        WHY_VISIT_PARA = "Immerse yourself in a land where rich history meets cutting-edge modernity. The United Kingdom promises an experience steeped in regal elegance, featuring medieval castles, rugged coastlines, and culturally vibrant cities. From luxurious afternoon teas in London to exploring the sweeping highlands of Scotland, it is an unforgettable adventure."
        BULLET_1 = "Prestigious castles and historical manors"
        BULLET_2 = "Exclusive dining and Michelin-starred restaurants in London"
        BULLET_3 = "Vast rolling moors and dramatic lakeside views"
        BULLET_4 = "Timeless traditions of English afternoon tea"
        BULLET_5 = "Access to the finest luxury retail at Harrods and Savile Row"
        EXP_TITLE = "Royal Heritage"
        EXP_1_IMG = "https://images.unsplash.com/photo-1520986606214-8b456906c813?q=80&w=600"
        EXP_1_TITLE = "Historic Landmarks"
        EXP_1_PARA = "Marvel at the Gothic architecture of Westminster Abbey and the majestic Tower Bridge."
        EXP_2_IMG = "https://images.unsplash.com/photo-1534065602492-421715ff1b5d?q=80&w=600"
        EXP_2_TITLE = "English Countryside"
        EXP_2_PARA = "Escape to the serene beauty of the Cotswolds with its honey-colored stone cottages."
        EXP_3_IMG = "https://images.unsplash.com/photo-1501504905252-473c47e087f8?q=80&w=600"
        EXP_3_TITLE = "Vibrant Capitals"
        EXP_3_PARA = "Experience the dynamic arts, theater, and cosmopolitan pulse of modern-day London."
        STORY_TITLE = "A Land of Legends"
        STORY_PARA = "You trace the footsteps of royalty and poets, finding luxury in cozy oak-paneled rooms and sprawling emerald estates that capture the essence of Britain."
        GAL_1 = "https://images.unsplash.com/photo-1529180231648-52e9ff6b34cf?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1518398046578-8cca57782e17?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1473625247510-8b1b5188f615?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1501504905252-473c47e087f8?q=80&w=800"
    }
    @{
        FILE = "japan.html"
        TITLE = "Japan"
        HERO_IMG = "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1600"
        HERO_TITLE = "Experience Japan"
        HERO_SUBTEXT = "A harmonious balance of ancient tradition and futuristic innovation."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1528360983277-13d401cdc186?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Japan"
        WHY_VISIT_PARA = "Japan invites you to an intoxicating blend of the past and the future. Experience the serene beauty of zen gardens and ancient temples, just a bullet train ride away from neon-soaked metropolis hubs. The reverence for perfection, unparalleled hospitality (omotenashi), and exquisite seasons will captivate your soul completely."
        BULLET_1 = "Tranquil shrines surrounded by brilliant cherry blossoms"
        BULLET_2 = "World-class sushi and immersive culinary mastery"
        BULLET_3 = "Luxurious ryokans featuring private hot springs (onsen)"
        BULLET_4 = "High-speed travel connecting diverse landscapes"
        BULLET_5 = "Vibrant youth culture intersecting with time-honored rituals"
        EXP_TITLE = "Zen & The Modern World"
        EXP_1_IMG = "https://images.unsplash.com/photo-1542051841857-5f90071e7989?q=80&w=600"
        EXP_1_TITLE = "Neon Citadels"
        EXP_1_PARA = "Navigate the electrifying streets of Tokyo, soaking in an unmatched cyberpunk aesthetic."
        EXP_2_IMG = "https://images.unsplash.com/photo-1557409518-691ebcd96038?q=80&w=600"
        EXP_2_TITLE = "Cultural Elegance"
        EXP_2_PARA = "Witness geishas traversing the historic alleyways of Kyoto amid stunning wooden architecture."
        EXP_3_IMG = "https://images.unsplash.com/photo-1504109586057-7a2ae83d1338?q=80&w=600"
        EXP_3_TITLE = "Nature's Embrace"
        EXP_3_PARA = "Find ultimate peace overlooking iconic Mt. Fuji or wandering through serene bamboo forests."
        STORY_TITLE = "A Symphony of Contrast"
        STORY_PARA = "Every day, Japan gifts you absolute perfection. From the meticulous brewing of matcha to the seamless precision of city life, you will feel entirely elevated."
        GAL_1 = "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1558862107-d49ef2a04d72?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1528360983277-13d401cdc186?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1542051841857-5f90071e7989?q=80&w=800"
    }
    @{
        FILE = "thailand.html"
        TITLE = "Thailand"
        HERO_IMG = "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=1600"
        HERO_TITLE = "Experience Thailand"
        HERO_SUBTEXT = "The land of smiles, pristine beaches, and golden temples."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1506665531195-3566af2b4dfa?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Thailand"
        WHY_VISIT_PARA = "Thailand weaves an exotic spell with its lush jungles, turquoise waters, and majestic golden temples. Feel perfectly pampered in five-star island resorts that seamlessly integrate with untouched nature. Thailand's vibrant energy ensures every moment is filled with warmth, luxury, and mesmerizing discovery."
        BULLET_1 = "Secluded luxury island resorts with pristine waters"
        BULLET_2 = "Majestic cultural landmarks and intricate temples"
        BULLET_3 = "World-renowned Thai massage and rejuvenating spas"
        BULLET_4 = "A kaleidoscope of flavorful street food and fine dining"
        BULLET_5 = "Vibrant night markets bursting with local treasures"
        EXP_TITLE = "Tropical Majesty"
        EXP_1_IMG = "https://images.unsplash.com/photo-1588631195000-0e1ce5da2f00?q=80&w=600"
        EXP_1_TITLE = "Island Paradises"
        EXP_1_PARA = "Sail through emerald waters surrounding the dramatic limestone cliffs of Phuket and Krabi."
        EXP_2_IMG = "https://images.unsplash.com/photo-1508009603885-24758b90159f?q=80&w=600"
        EXP_2_TITLE = "Temple Serenity"
        EXP_2_PARA = "Marvel at the soaring, intricately decorated spires of Bangkok's Grand Palace."
        EXP_3_IMG = "https://images.unsplash.com/photo-1558564245-c4cf4b4cfde4?q=80&w=600"
        EXP_3_TITLE = "Jungle Retreats"
        EXP_3_PARA = "Experience deep tranquility and ethical elephant encounters in the jungles of Chiang Mai."
        STORY_TITLE = "Eternal Sunshine"
        STORY_PARA = "You find rhythm by the sea, enjoying fiery sunsets and the lingering fragrance of lemongrass in the air—an exotic paradise you'll never want to leave."
        GAL_1 = "https://images.unsplash.com/photo-1510805569426-ed87dbfce4b3?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1528652395568-d6c703b7fc14?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1537233267576-9d5ced4ae234?q=80&w=800"
    }
    @{
        FILE = "malaysia.html"
        TITLE = "Malaysia"
        HERO_IMG = "https://images.unsplash.com/photo-1596422846543-7f9da529c2ab?q=80&w=1600"
        HERO_TITLE = "Experience Malaysia"
        HERO_SUBTEXT = "A true melting pot of striking skylines and ancient rainforests."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1518002171953-a080ee817e1f?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Malaysia"
        WHY_VISIT_PARA = "Malaysia offers a captivating dynamic where pristine 130-million-year-old rainforests meet the ultra-modern skyline of Kuala Lumpur. This diversity translates into a rich tapestry of experiences, combining elite cosmopolitan luxury with breathtaking eco-tourism. Lose yourself in diverse culinary legacies and absolute tropical splendor."
        BULLET_1 = "Iconic skyscrapers like the Petronas Twin Towers"
        BULLET_2 = "Deep jungles and luxury eco-retreats in Borneo"
        BULLET_3 = "White-sand beaches and azure waters in Langkawi"
        BULLET_4 = "Historical colonial charm found in Penang"
        BULLET_5 = "Incredible multicultural cuisine blending Asian flavors"
        EXP_TITLE = "A Cultural Mosaic"
        EXP_1_IMG = "https://images.unsplash.com/photo-1574512999496-c14828131336?q=80&w=600"
        EXP_1_TITLE = "Urban Splendor"
        EXP_1_PARA = "Shop at the finest high-end malls in Kuala Lumpur and dine in the sky."
        EXP_2_IMG = "https://images.unsplash.com/photo-1563854617-64cd5fe5ee47?q=80&w=600"
        EXP_2_TITLE = "Nature's Secrets"
        EXP_2_PARA = "Dive into vibrant coral reefs or explore the mysterious, sprawling Batu Caves."
        EXP_3_IMG = "https://images.unsplash.com/photo-1520677579624-a74fcbb3205a?q=80&w=600"
        EXP_3_TITLE = "Heritage Trails"
        EXP_3_PARA = "Stroll the vibrant, art-filled streets of Georgetown and sample endless hawker delights."
        STORY_TITLE = "Heart of Diversity"
        STORY_PARA = "Every corner of Malaysia sings with life. You will embrace a kaleidoscope of cultures, finding luxury everywhere from the sleek megacities to the quiet jungle canopy."
        GAL_1 = "https://images.unsplash.com/photo-1521634839212-d8a417df854e?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1518002171953-a080ee817e1f?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1574512999496-c14828131336?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1596422846543-7f9da529c2ab?q=80&w=800"
    }
    @{
        FILE = "srilanka.html"
        TITLE = "Sri Lanka"
        HERO_IMG = "https://images.unsplash.com/photo-1586227740560-8cf2732c1531?q=80&w=1600"
        HERO_TITLE = "Experience Sri Lanka"
        HERO_SUBTEXT = "The pearl of the Indian Ocean waiting to be discovered."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1546708973-b339540b5162?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Sri Lanka"
        WHY_VISIT_PARA = "Endless beaches, timeless ruins, welcoming people, oodles of elephants, rolling surf, cheap prices, fun trains, famous tea and flavorful food make Sri Lanka irresistible. You will find yourself retreating in stunning boutique villas hidden amidst verdant tea plantations."
        BULLET_1 = "Stunning colonial-era tea plantations in Nuwara Eliya"
        BULLET_2 = "Golden surf beaches along the wild southern coast"
        BULLET_3 = "Majestic elephants roaming freely in national parks"
        BULLET_4 = "Historic UNESCO World Heritage sites like Sigiriya"
        BULLET_5 = "World-renowned Ayurvedic wellness and spa retreats"
        EXP_TITLE = "Island of Serenity"
        EXP_1_IMG = "https://images.unsplash.com/photo-1555513257-2c9bd4eafb04?q=80&w=600"
        EXP_1_TITLE = "Spiritual Heritage"
        EXP_1_PARA = "Climb the ancient rock fortress of Sigiriya overlooking the vast plains."
        EXP_2_IMG = "https://images.unsplash.com/photo-1586227740560-8cf2732c1531?q=80&w=600"
        EXP_2_TITLE = "Tea Country"
        EXP_2_PARA = "Take the stunning blue train sweeping through misty, lush green highland estates."
        EXP_3_IMG = "https://images.unsplash.com/photo-1502444330042-d1a1ddf0011e?q=80&w=600"
        EXP_3_TITLE = "Coastal Solitude"
        EXP_3_PARA = "Watch beautiful sunsets reflecting off palm-fringed, golden sandy beaches."
        STORY_TITLE = "The Tear Drop of the Ocean"
        STORY_PARA = "In Sri Lanka, luxury is found in the untouched grace of nature, allowing you to reconnect deeply with the earth and yourself."
        GAL_1 = "https://images.unsplash.com/photo-1546708973-b339540b5162?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1586227740560-8cf2732c1531?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1520106212299-d99c443e4568?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1555513257-2c9bd4eafb04?q=80&w=800"
    }
    @{
        FILE = "hongkong.html"
        TITLE = "Hong Kong"
        HERO_IMG = "https://images.unsplash.com/photo-1506501139174-099022df5260?q=80&w=1600"
        HERO_TITLE = "Experience Hong Kong"
        HERO_SUBTEXT = "The glowing pulse of Asia where tradition meets tomorrow."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Hong Kong"
        WHY_VISIT_PARA = "Hong Kong is a cinematic cityscape of staggering ambition, where densely packed neon streets collide with sweeping peaks and sparkling harbors. It pulses with infectious energy. From its legendary Michelin-starred dim sum to its world-class luxury shopping, the city guarantees a breathless rhythm of discovery."
        BULLET_1 = "Jaw-dropping, neon-lit iconic skyline views"
        BULLET_2 = "World’s best culinary scene blending East and West"
        BULLET_3 = "Lush green hiking trails just minutes from the city center"
        BULLET_4 = "Historical ferries crossing the magnificent Victoria Harbour"
        BULLET_5 = "Unmatched high-end boutique shopping districts"
        EXP_TITLE = "Neon Vistas"
        EXP_1_IMG = "https://images.unsplash.com/photo-1516086208573-f94de3a84ed0?q=80&w=600"
        EXP_1_TITLE = "Victoria Peak"
        EXP_1_PARA = "Stand above the clouds and gaze down at the breathtaking urban galaxy below."
        EXP_2_IMG = "https://images.unsplash.com/photo-1560963503-4552cf34e7dd?q=80&w=600"
        EXP_2_TITLE = "Gourmet Excellence"
        EXP_2_PARA = "Sample everything from sizzling street-side woks to opulent fine dining."
        EXP_3_IMG = "https://images.unsplash.com/photo-1555621406-8ae13dbe42f2?q=80&w=600"
        EXP_3_TITLE = "Secret Nature"
        EXP_3_PARA = "Escape the concrete jungle by stepping into quiet fishing villages and island retreats."
        STORY_TITLE = "A City That Never Sleeps"
        STORY_PARA = "Bathed in the glow of endless signs and soaring towers, Hong Kong electrifies your senses, leaving an indelible imprint of modern magnificence."
        GAL_1 = "https://images.unsplash.com/photo-1506501139174-099022df5260?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1516086208573-f94de3a84ed0?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1560963503-4552cf34e7dd?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?q=80&w=800"
    }
    @{
        FILE = "china.html"
        TITLE = "China"
        HERO_IMG = "https://images.unsplash.com/photo-1508804052814-c32222f281e2?q=80&w=1600"
        HERO_TITLE = "Experience China"
        HERO_SUBTEXT = "A vast empire of staggering natural beauty and immense history."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit China"
        WHY_VISIT_PARA = "China is an awakening giant connecting the ancient world to the futuristic edge. Embark on a luxurious journey through immense dynastic palaces, stroll atop the Great Wall, and marvel at soaring glass towers spanning massive rivers. It is a country that offers unparalleled scope, scale, and rich heritage."
        BULLET_1 = "Millennia-old wonders like the Great Wall and Forbidden City"
        BULLET_2 = "Ultramodern marvels in Shanghai's dazzling skyline"
        BULLET_3 = "Otherworldly natural landscapes like the Avatar mountains"
        BULLET_4 = "Elegant traditional tea ceremonies in silent pavilions"
        BULLET_5 = "Luxury bullet trains charting across the vast nation"
        EXP_TITLE = "Ancient Wisdom, Modern Power"
        EXP_1_IMG = "https://images.unsplash.com/photo-1584345624796-03c6dd06da91?q=80&w=600"
        EXP_1_TITLE = "Imperial Grandeur"
        EXP_1_PARA = "Feel the awe of ancient emperors inside the meticulously preserved Forbidden City."
        EXP_2_IMG = "https://images.unsplash.com/photo-1543169724-4f5ef4fa221a?q=80&w=600"
        EXP_2_TITLE = "Shanghai Nights"
        EXP_2_PARA = "Dine in glowing towers overlooking the magnificent architecture of The Bund."
        EXP_3_IMG = "https://images.unsplash.com/photo-1551041777-ed277b8dd348?q=80&w=600"
        EXP_3_TITLE = "Natural Splendor"
        EXP_3_PARA = "Sail through the mystical karst mountains along the serene Li River."
        STORY_TITLE = "The Dragon Awakens"
        STORY_PARA = "From silent temples draped in mist to the sprawling megalopolises, China envelops you in an epic tale of humanity’s grandeur."
        GAL_1 = "https://images.unsplash.com/photo-1508804052814-c32222f281e2?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1584345624796-03c6dd06da91?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1551041777-ed277b8dd348?q=80&w=800"
    }
)

foreach ($page in $pages) {
    $out = $template
    foreach ($key in $page.Keys) {
        $placeholder = "{{$key}}"
        $value = $page[$key]
        $out = $out.Replace($placeholder, $value)
    }
    # Clear active state for Bali explicitly on new pages
    $out = $out -replace '<li class="active"><a href="bali.html">', '<li><a href="bali.html">'
    $activeString = '<li><a href="' + $page.FILE + '">'
    $activeReplacement = '<li class="active"><a href="' + $page.FILE + '">'
    $out = $out.Replace($activeString, $activeReplacement)

    Set-Content -Path $page.FILE -Value $out -Encoding UTF8
    Write-Host "Generated $($page.FILE)"
}

