$template = Get-Content -Raw "dest_template.html"

$pages = @(
    @{
        FILE = "kashmir.html"
        TITLE = "Kashmir"
        HERO_IMG = "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?q=80&w=1600"
        HERO_TITLE = "Experience Kashmir"
        HERO_SUBTEXT = "Paradise on Earth wrapped in the breathtaking Himalayas."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1566837497312-7c8d9df1552a?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Kashmir"
        WHY_VISIT_PARA = "Kashmir's surreal landscapes feel like stepping into an ancient painting. Experience profound tranquility gliding across mirrored lakes in a magnificent wooden houseboat. From fiery autumn chinar trees to pristine, snow-blanketed valleys echoing softly against the mountains, Kashmir promises the ultimate serene escape for your soul."
        BULLET_1 = "Luxurious heritage houseboats on the serene Dal Lake"
        BULLET_2 = "World-class skiing down the powdery slopes of Gulmarg"
        BULLET_3 = "Vibrant Mughal gardens blooming with exotic flowers"
        BULLET_4 = "Exclusive artisanal cashmere and intricate saffron trades"
        BULLET_5 = "Trekking trails through remote alpine meadows"
        EXP_TITLE = "Himalayan Majesty"
        EXP_1_IMG = "https://images.unsplash.com/photo-1620024419910-67df76ee7b2c?q=80&w=600"
        EXP_1_TITLE = "Shikara Serenity"
        EXP_1_PARA = "Glide gracefully across Dal Lake as the setting sun reflects off the surrounding snowy peaks."
        EXP_2_IMG = "https://images.unsplash.com/photo-1620165362092-d34485127029?q=80&w=600"
        EXP_2_TITLE = "Snow-Capped Peaks"
        EXP_2_PARA = "Experience the unparalleled thrill of taking the highest gondola rides atop Gulmarg."
        EXP_3_IMG = "https://images.unsplash.com/photo-1601002271811-9a7f3efb2a95?q=80&w=600"
        EXP_3_TITLE = "Royal Gardens"
        EXP_3_PARA = "Lose yourself in the symmetry and fragrance of ancient terraced Mughal landscapes."
        STORY_TITLE = "A Timeless Poem"
        STORY_PARA = "In Kashmir, the air is crisp, the hospitality is warm, and time seems beautifully frozen in a world of absolute purity and grandeur."
        GAL_1 = "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1566837497312-7c8d9df1552a?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1620024419910-67df76ee7b2c?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1601002271811-9a7f3efb2a95?q=80&w=800"
    }
    @{
        FILE = "ladakh.html"
        TITLE = "Leh Ladakh"
        HERO_IMG = "https://images.unsplash.com/photo-1580133171881-8b29c9cc0881?q=80&w=1600"
        HERO_TITLE = "Experience Ladakh"
        HERO_SUBTEXT = "Venture into the pristine silence of the high-altitude desert."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Leh Ladakh"
        WHY_VISIT_PARA = "Ladakh is a mystical land where azure skies perfectly frame barren mountains and vibrant prayer flags flutter in the wind. This high-altitude desert challenges the adventurous while providing incredibly luxurious tented camps catering to those who desire exploration without sacrificing absolute comfort. It truly is the roof of the world."
        BULLET_1 = "Glamping under the endless canopy of the Milky Way"
        BULLET_2 = "Awe-inspiring vistas at the bright blue Pangong Lake"
        BULLET_3 = "Conquering Khardung La, one of the world's highest motorable passes"
        BULLET_4 = "Centuries-old Tibetan monasteries hanging on cliff sides"
        BULLET_5 = "Charming encounters with elusive Himalayan wildlife"
        EXP_TITLE = "The High Frontier"
        EXP_1_IMG = "https://images.unsplash.com/photo-1618084705574-8804cd1540cc?q=80&w=600"
        EXP_1_TITLE = "Sapphire Lakes"
        EXP_1_PARA = "Witness the mirror-like perfection of Pangong Tso extending endlessly to Tibet."
        EXP_2_IMG = "https://images.unsplash.com/photo-1596706965158-6dc92d6e2e50?q=80&w=600"
        EXP_2_TITLE = "Monastic Marvels"
        EXP_2_PARA = "Hear the deep rolling chants echoing from Thiksey Monastery."
        EXP_3_IMG = "https://images.unsplash.com/photo-1610403328246-17b07dbf1725?q=80&w=600"
        EXP_3_TITLE = "Desert Safari"
        EXP_3_PARA = "Ride a double-humped Bactrian camel through the surreal Nubra Valley dunes."
        STORY_TITLE = "The Edge of the Sky"
        STORY_PARA = "Breathing in the thin, pure mountain air, you’ll realize the immense scale of this landscape, humbling and uplifting your spirit all at once."
        GAL_1 = "https://images.unsplash.com/photo-1580133171881-8b29c9cc0881?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1618084705574-8804cd1540cc?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1596706965158-6dc92d6e2e50?q=80&w=800"
    }
    @{
        FILE = "himachal.html"
        TITLE = "Himachal Pradesh"
        HERO_IMG = "https://images.unsplash.com/photo-1605640840482-15ea46edebdf?q=80&w=1600"
        HERO_TITLE = "Experience Himachal"
        HERO_SUBTEXT = "Discover the majestic valleys of the gods."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1626714486510-2b1d33cbfa2f?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Himachal"
        WHY_VISIT_PARA = "Nestled deep in the western Himalayas, Himachal Pradesh boasts enchanting valleys covered in thick emerald pine and sparkling snow. Retreat to luxury heritage cottages perched beautifully upon misty mountain cliffs. Lose track of time enjoying crackling fires, slow trails, and incredible local warmth."
        BULLET_1 = "Boutique woodland cottages providing breathtaking panoramas"
        BULLET_2 = "Iconic lush valleys like Kullu, Manali, and Spiti"
        BULLET_3 = "Gourmet mountain dining starring fresh regional produce"
        BULLET_4 = "Adrenaline-fueled river rafting and elevated paragliding"
        BULLET_5 = "Charming, historic tea estates nestled in Kangra"
        EXP_TITLE = "Mountain Retreats"
        EXP_1_IMG = "https://images.unsplash.com/photo-1593693397987-1481eeba9d88?q=80&w=600"
        EXP_1_TITLE = "Valley Escapes"
        EXP_1_PARA = "Walk silently through apple orchards that carpet the majestic mountainsides."
        EXP_2_IMG = "https://images.unsplash.com/photo-1605640840482-15ea46edebdf?q=80&w=600"
        EXP_2_TITLE = "Spiritual Quiet"
        EXP_2_PARA = "Listen to the quiet prayers flowing from hilltop monasteries in Dharamshala."
        EXP_3_IMG = "https://images.unsplash.com/photo-1615486171448-4fd32577ea53?q=80&w=600"
        EXP_3_TITLE = "High Passes"
        EXP_3_PARA = "Navigate the soaring Rohtang Pass, a pure white heaven for snow lovers."
        STORY_TITLE = "Above the Clouds"
        STORY_PARA = "Morning tea arrives as the valley clears of mist. For a moment, the vast, echoing mountain silence is all you hear—absolute perfection."
        GAL_1 = "https://images.unsplash.com/photo-1605640840482-15ea46edebdf?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1626714486510-2b1d33cbfa2f?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1593693397987-1481eeba9d88?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1615486171448-4fd32577ea53?q=80&w=800"
    }
    @{
        FILE = "kerala.html"
        TITLE = "Kerala"
        HERO_IMG = "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1600"
        HERO_TITLE = "Experience Kerala"
        HERO_SUBTEXT = "Sail into the serene heart of God's Own Country."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1593693397987-1481eeba9d88?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Kerala"
        WHY_VISIT_PARA = "Glide gracefully along emerald backwaters while ensconced safely within a traditional luxury houseboat. Kerala offers an ethereal retreat surrounded by rich, unending greenery, golden beaches, and fragrant spice plantations. It is a slow, deeply restorative haven dedicated to the absolute luxury of unwinding."
        BULLET_1 = "Private, traditional teak kettuvallams (houseboats)"
        BULLET_2 = "World-class immersive Ayurvedic treatments and wellness"
        BULLET_3 = "Tranquil mist-covered tea estates in Munnar"
        BULLET_4 = "Untouched palm-lined beaches by the Arabian Sea"
        BULLET_5 = "Vibrant local flavors bursting with fresh coconut and spices"
        EXP_TITLE = "Backwaters & Bliss"
        EXP_1_IMG = "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=600"
        EXP_1_TITLE = "Houseboat Journeys"
        EXP_1_PARA = "Drift slowly under sleepy palm canopies as village life unfolds beside you."
        EXP_2_IMG = "https://images.unsplash.com/photo-1536768789397-5b6826372138?q=80&w=600"
        EXP_2_TITLE = "Ayurvedic Healing"
        EXP_2_PARA = "Rejuvenate completely in premium wellness sanctuaries nestled in the jungle."
        EXP_3_IMG = "https://images.unsplash.com/photo-1551390453-27083049ba32?q=80&w=600"
        EXP_3_TITLE = "Tea Plantations"
        EXP_3_PARA = "Spend mornings tasting the finest tea atop the stunning rolling hills of Munnar."
        STORY_TITLE = "A Rhythm of Green"
        STORY_PARA = "There is a profound stillness in Kerala. The gentle lapping of backwaters and the soft rustle of palms coax you into complete inner peace."
        GAL_1 = "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1593693397987-1481eeba9d88?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1536768789397-5b6826372138?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1551390453-27083049ba32?q=80&w=800"
    }
    @{
        FILE = "goa.html"
        TITLE = "Goa"
        HERO_IMG = "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1600"
        HERO_TITLE = "Experience Goa"
        HERO_SUBTEXT = "A mesmerizing cocktail of luxury, heritage, and golden shores."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Goa"
        WHY_VISIT_PARA = "Beyond the vibrant coastline lies a Goa of unmatched luxury. Discover hidden boutique villas swathed in Portuguese heritage, where lazy afternoons effortlessly melt into exquisite evenings. Let the sound of the ocean frame your every moment, and the slow, rhythmic susegad lifestyle take all your worries away."
        BULLET_1 = "Private stunning beach coves lined by five-star resorts"
        BULLET_2 = "Exquisite Portuguese-era heritage architecture"
        BULLET_3 = "Sophisticated beach clubs and exclusive dining spots"
        BULLET_4 = "Pristine yacht charters across the Arabian Sea"
        BULLET_5 = "Tranquil yoga sanctuaries wrapped deep in tropical rainforests"
        EXP_TITLE = "The Golden Coast"
        EXP_1_IMG = "https://images.unsplash.com/photo-1558231868-b789d9c221cf?q=80&w=600"
        EXP_1_TITLE = "Beachside Luxury"
        EXP_1_PARA = "Lounge on immaculate sands with a chilled drink, hosted by world-class concierges."
        EXP_2_IMG = "https://images.unsplash.com/photo-1549420955-dc0a228f41f7?q=80&w=600"
        EXP_2_TITLE = "Heritage Trails"
        EXP_2_PARA = "Explore old, majestic churches painted beautiful white under the tropical sun."
        EXP_3_IMG = "https://images.unsplash.com/photo-1590483864082-f542456fc5e9?q=80&w=600"
        EXP_3_TITLE = "Culinary Feasts"
        EXP_3_PARA = "Feast on incredibly fresh seafood curated continuously by acclaimed global chefs."
        STORY_TITLE = "The Susegad Life"
        STORY_PARA = "Time doesn’t rule here. The only schedule is set by the glowing orange sunsets and the gentle rolling tides."
        GAL_1 = "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1558231868-b789d9c221cf?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1549420955-dc0a228f41f7?q=80&w=800"
    }
    @{
        FILE = "ooty.html"
        TITLE = "Ooty"
        HERO_IMG = "https://images.unsplash.com/photo-1598284560756-74fc2ef99e03?q=80&w=1600"
        HERO_TITLE = "Experience Ooty"
        HERO_SUBTEXT = "Retreat to the aristocratic mist of the Nilgiris."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1602166567156-f60bece3507c?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Ooty"
        WHY_VISIT_PARA = "Step into a world reminiscent of classic colonial elegance. Ooty presents sweeping emerald hills enveloped endlessly in mist. Relax beside warm stone fireplaces inside magnificent heritage planters' mansions, and wake up to the glorious smell of fresh eucalyptus drifting through the crisp morning valleys."
        BULLET_1 = "Staying in meticulously restored British colonial mansions"
        BULLET_2 = "Scenic journeys on the historic Nilgiri Mountain Railway"
        BULLET_3 = "Wandering through wildly beautiful botanical gardens"
        BULLET_4 = "Exclusive tea tasting sessions from premium local estates"
        BULLET_5 = "Idyllic boating across tranquil fog-laden lakes"
        EXP_TITLE = "The Queen of Hills"
        EXP_1_IMG = "https://images.unsplash.com/photo-1598284560756-74fc2ef99e03?q=80&w=600"
        EXP_1_TITLE = "Heritage Living"
        EXP_1_PARA = "Immerse yourself in history inside beautifully antiquated luxury bungalows."
        EXP_2_IMG = "https://images.unsplash.com/photo-1601003668388-75c1c8a666e6?q=80&w=600"
        EXP_2_TITLE = "Toy Train Escapes"
        EXP_2_PARA = "Wind your way magically through towering forests of eucalyptus and pine tunnels."
        EXP_3_IMG = "https://images.unsplash.com/photo-1602166567156-f60bece3507c?q=80&w=600"
        EXP_3_TITLE = "Verdant Slopes"
        EXP_3_PARA = "Trek quietly along endless ridges of fragrant and sprawling tea plantations."
        STORY_TITLE = "Mist and Memories"
        STORY_PARA = "With a warm cup of Nilgiri tea in your hands, observing the fog roll gently across the mountains, life feels incredibly light."
        GAL_1 = "https://images.unsplash.com/photo-1598284560756-74fc2ef99e03?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1602166567156-f60bece3507c?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1601003668388-75c1c8a666e6?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1598284560756-74fc2ef99e03?q=80&w=800"
    }
    @{
        FILE = "delhi.html"
        TITLE = "Delhi"
        HERO_IMG = "https://images.unsplash.com/photo-1587474260584-136574528ed5?q=80&w=1600"
        HERO_TITLE = "Experience Delhi"
        HERO_SUBTEXT = "The spectacular crossroads of ancient empires and modern luxury."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1574872221626-d62f79020473?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Delhi"
        WHY_VISIT_PARA = "Delhi is a vibrant titan of culture. Walk the incredible corridors of ancient Mughal forts before unwinding in the most sophisticated, high-end suites in the nation. It is a city of layered history, where culinary brilliance meets endless diplomatic luxury, offering an experience both profoundly deep and thrillingly lavish."
        BULLET_1 = "Five-star luxury within striking distance of ancient monuments"
        BULLET_2 = "Unmatched fine dining featuring exquisite royal Indian cuisine"
        BULLET_3 = "Majestic UNESCO heritage sights like Humayun's Tomb"
        BULLET_4 = "Exclusive high-end boutiques and sprawling artisan markets"
        BULLET_5 = "Charming heritage walks tracing the shadows of past empires"
        EXP_TITLE = "A Tale of Two Cities"
        EXP_1_IMG = "https://images.unsplash.com/photo-1587474260584-136574528ed5?q=80&w=600"
        EXP_1_TITLE = "Mughal Grandeur"
        EXP_1_PARA = "Marvel at the spectacular red sandstone arches of the massive Red Fort."
        EXP_2_IMG = "https://images.unsplash.com/photo-1574872221626-d62f79020473?q=80&w=600"
        EXP_2_TITLE = "Lutyens Elegance"
        EXP_2_PARA = "Take a serene evening drive through the expansive geometries of New Delhi."
        EXP_3_IMG = "https://images.unsplash.com/photo-1591500096645-888e22830fcc?q=80&w=600"
        EXP_3_TITLE = "Culinary Empires"
        EXP_3_PARA = "Feast on rich kebabs and royal curries crafted by master traditional chefs."
        STORY_TITLE = "The Heartbeat of India"
        STORY_PARA = "As the setting sun glows off medieval stone walls, you witness a city that has conquered time—standing endlessly proud and incredibly alive."
        GAL_1 = "https://images.unsplash.com/photo-1587474260584-136574528ed5?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1574872221626-d62f79020473?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1591500096645-888e22830fcc?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1574872221626-d62f79020473?q=80&w=800"
    }
    @{
        FILE = "mumbai.html"
        TITLE = "Mumbai"
        HERO_IMG = "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?q=80&w=1600"
        HERO_TITLE = "Experience Mumbai"
        HERO_SUBTEXT = "The city of glittering dreams and unyielding ambition."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Mumbai"
        WHY_VISIT_PARA = "Mumbai spins a dazzling web of vintage charm and massive modern wealth. Sleep wrapped in the legendary heritage of sea-facing iconic hotels, dine over glittering skylines, and dive into the glamorous whirlwind of Bollywood. It perfectly defines dynamic luxury, offering an electric pulse you will feel everywhere."
        BULLET_1 = "Staying at timeless heritage properties like the Taj Mahal Palace"
        BULLET_2 = "Exclusive rooftop parties viewing the sparkling Marine Drive"
        BULLET_3 = "Gourmet coastal cuisine served in high-fashion districts"
        BULLET_4 = "Sailing quietly on private yachts launching from the Gateway of India"
        BULLET_5 = "Incredible Victorian-Gothic architecture weaving through the south city"
        EXP_TITLE = "The Glamour & Glory"
        EXP_1_IMG = "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?q=80&w=600"
        EXP_1_TITLE = "Heritage Trails"
        EXP_1_PARA = "Step back into the elegant 19th-century splendor of South Mumbai streets."
        EXP_2_IMG = "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?q=80&w=600"
        EXP_2_TITLE = "The Queen's Necklace"
        EXP_2_PARA = "Gaze over the stunning arc of sparkling lights tracing the vast ocean bay."
        EXP_3_IMG = "https://images.unsplash.com/photo-1567156949303-3467b45a305f?q=80&w=600"
        EXP_3_TITLE = "Ocean Excursions"
        EXP_3_PARA = "Leave the hustle behind on a quiet luxury sailboat tracking the sunset."
        STORY_TITLE = "A City Made of Stars"
        STORY_PARA = "There is an irresistible electric charge in Mumbai’s air. Every night promises a brilliant glow, wrapping its visitors in an undeniably glamorous spell."
        GAL_1 = "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1567156949303-3467b45a305f?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?q=80&w=800"
    }
    @{
        FILE = "gujarat.html"
        TITLE = "Gujarat"
        HERO_IMG = "https://images.unsplash.com/photo-1558431382-27e303142255?q=80&w=1600"
        HERO_TITLE = "Experience Gujarat"
        HERO_SUBTEXT = "A majestic land of legends, lions, and vast white deserts."
        WHY_VISIT_IMG = "https://images.unsplash.com/photo-1582298751520-21a1661158a1?q=80&w=800"
        WHY_VISIT_TITLE = "Why Visit Gujarat"
        WHY_VISIT_PARA = "Immerse yourself in a royal kingdom that guards the brilliant white salt flats of the Rann. Gujarat invites you to experience supreme luxury tents under moonlit skies and breathtaking close encounters with Asiatic lions. The colors here are intensely vibrant, the history remarkably profound, and the culture beautifully welcoming."
        BULLET_1 = "Glamorous moonlit stays precisely upon the White Rann desert"
        BULLET_2 = "Exclusive safaris safely exploring the regal Gir Forest lions"
        BULLET_3 = "Magnificent heritage palace stays originally built by royal families"
        BULLET_4 = "Magnificent ancient stepwells featuring jaw-dropping architecture"
        BULLET_5 = "Vibrant traditional textiles and extraordinarily colorful handicrafts"
        EXP_TITLE = "A Kingdom of Colors"
        EXP_1_IMG = "https://images.unsplash.com/photo-1558431382-27e303142255?q=80&w=600"
        EXP_1_TITLE = "The White Desert"
        EXP_1_PARA = "Watch the infinite salt crystal plains gleam stunningly beneath the full moon."
        EXP_2_IMG = "https://images.unsplash.com/photo-1582298751520-21a1661158a1?q=80&w=600"
        EXP_2_TITLE = "Royal Heritage"
        EXP_2_PARA = "Indulge your senses walking the grand corridors of immense historic palaces."
        EXP_3_IMG = "https://images.unsplash.com/photo-1596482165241-11b333ac7a39?q=80&w=600"
        EXP_3_TITLE = "Divine Marvels"
        EXP_3_PARA = "Experience immense peace viewing the intricate carvings inside ancient spiritual temples."
        STORY_TITLE = "Songs of the Sand"
        STORY_PARA = "In Gujarat, the setting sun casts a mystical glow over ancient lands. It is a deeply grounding experience that perfectly merges regal comfort with the vast wilds."
        GAL_1 = "https://images.unsplash.com/photo-1558431382-27e303142255?q=80&w=800"
        GAL_2 = "https://images.unsplash.com/photo-1582298751520-21a1661158a1?q=80&w=800"
        GAL_3 = "https://images.unsplash.com/photo-1596482165241-11b333ac7a39?q=80&w=800"
        GAL_4 = "https://images.unsplash.com/photo-1582298751520-21a1661158a1?q=80&w=800"
    }
)

foreach ($page in $pages) {
    $out = $template
    foreach ($key in $page.Keys) {
        $placeholder = "{{$key}}"
        $value = $page[$key]
        $out = $out.Replace($placeholder, $value)
    }
    # Clear active state for Bali explicitly on new pages
    $out = $out -replace '<li class="active"><a href="bali.html">', '<li><a href="bali.html">'
    $activeString = '<li><a href="' + $page.FILE + '">'
    $activeReplacement = '<li class="active"><a href="' + $page.FILE + '">'
    $out = $out.Replace($activeString, $activeReplacement)

    Set-Content -Path $page.FILE -Value $out -Encoding UTF8
    Write-Host "Generated $($page.FILE)"
}

